### ISSUE TITLE
URL slash issue

### ISSUE THREAD

**Issue by note103** [Songmu/p5-Riji#13]
通常、URLを記載する場合にはこのように書いて、
![riji-url-2](https://cloud.githubusercontent.com/assets/970686/4174223/3f3afdce-3580-11e4-897a-e80ddcb4c1b8.png)

普通に `riji publish` できるのですが、
![riji-url-3](https://cloud.githubusercontent.com/assets/970686/4174221/3f357fa2-3580-11e4-9bc5-81d975afd563.png)

`http:`の後の`/`を抜いて、
![riji-url-4](https://cloud.githubusercontent.com/assets/970686/4174224/3f3bb548-3580-11e4-9320-c50f3c6ef68a.png)

commitして、
![riji-url-5](https://cloud.githubusercontent.com/assets/970686/4174226/3f43a960-3580-11e4-81e2-c77a24b32678.png)

'riji publish'するとerrorが出ます。
![riji-url-6](https://cloud.githubusercontent.com/assets/970686/4174225/3f41c50a-3580-11e4-9980-b68fb4741d45.png)

最初、これが出続けた時に何が原因かわからなくて、突き止めるまでちょっと時間がかかったので、ご報告しました。

**Comment by Songmu** [comment]
報告ありがとうございます。放置しててすみません。

この問題ってまだ起こってますかね？手元では再現できませんでした…。

**Comment by note103** [comment]
> この問題ってまだ起こってますかね？手元では再現できませんでした…。いつの間にか治っていたパターンかも知れません。

なるほど、了解しました。あとで以前と同じ環境でまた試して、報告します。

> というのと、警告がでるだけでサイト生成自体は問題なくできているってことですよね？

そうですね。処理が途中で止まる、とかではありません。ただ、エラーの方が印象に残ってしまって、実際その部分がどう生成されていたか、ということを忘れてしまったので、その点も合わせて確認してみます。

**Comment by note103** [comment]
@Songmu あらためて確認しましたら、おっしゃる通りで、こちらでも直っていました。

今は5.20.0を使っていますが、issueを立てた時は5.18.2だったので、念のため両方で試しましたが、両方とも大丈夫でした。

僕の方もissueを立てた後はとくに確認していなかったので、いつ頃から再現しなくなったのか、ちょっとわからないのですが、かえってお手数をおかけしてしまって、すみません。
ご確認、ありがとうございました。

ということで、closeします。

**Comment by Songmu** [comment]
ありがとうございます！

**Comment by note103** [comment]
@Songmu すみません、一点、直近の検証時に抜けていた要素があり、URLを `< >` でくくらなければ何も問題なかったのですが、くくったら同じエラーが出ました。

つまりMarkdownファイル内で、スラッシュ2本の所を1本にして

```
 https:/www.google.co.jp/
```

と書くぶんには大丈夫なのですが、

```
<https:/www.google.co.jp/>
```

とすると、最初に報告したエラーが出ました。（今回は5.20.0にて）

ただ、ご推察のとおり、サイト生成自体は問題なく出来ており（サイト上にそのスラッシュが足りないリンク文字列が出てくる）、またエラーメッセージが出てくる事についても、書き手が記述ミスをしなければ済むことでもありますので、ひとまずIssue自体は閉じたままであらためてご報告します。
